language: objective-c
osx_image: xcode10

script:
- set -o pipefail && xcodebuild -project SYTagLabel.xcodeproj -allowProvisioningUpdates | xcpretty

after_success:
- bash <(curl -s https://codecov.io/bash)
